import React from 'react';
import type { Metadata } from 'next';
import EmotionProvider from '@/lib/provider/emotion';
import { Analytics } from '@vercel/analytics/react';
import { GoogleAnalytics, GoogleTagManager } from '@next/third-parties/google';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <EmotionProvider>{children}</EmotionProvider>
        <Analytics />
        <GoogleAnalytics gaId="G-XGEN5CYEMM" />
        <GoogleTagManager gtmId="GTM-P25D6R48" />
      </body>
    </html>
  );
}
